name: test
on:
  pull_request:
    types: [opened, edited]
jobs:
  pullOne:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm run test
