name: my_test
on:
  pull_request:
    types: [opened, edited]
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
  run_test:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run tes
